name: Mutation tests
on: [ push, pull_request ]

jobs:
    run:
        name: Mutation tests ${{ matrix.php }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ ubuntu-latest ]
                php: [ '8.0' ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: pcov
                    php-version: ${{ matrix.php }}
                    ini-values: memory_limit=-1
                    tools: composer:v2, cs2pr

            -   name: Determine composer cache directory
                id: composer-cache
                run: echo "::set-output name=directory::$(composer config cache-dir)"

            -   name: Cache composer dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.directory }}
                    key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ matrix.php }}-composer-

            -   name: Install Dependencies
                run: composer update --no-progress --ansi

            -   name: Infection
                run: ./vendor/bin/infection
                env:
                    INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
                    STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
